/**
 * Sangati AI — Alert Taxonomy Types
 *
 * Defines the structure for alert types, severities, and routing.
 * Matches the JSON schema at prototypes/alert-taxonomy/taxonomy.schema.json
 */

// --- Severity Levels ---

export type Severity = 'low' | 'medium' | 'high' | 'critical';

export const SEVERITY_ORDER: Record<Severity, number> = {
  low: 0,
  medium: 1,
  high: 2,
  critical: 3,
};

// --- Recipient Roles ---

export type RecipientRole = 'server' | 'captain' | 'manager' | 'kitchen' | 'all';

// --- Zone States ---

export type ZoneState = 'EMPTY' | 'OCCUPIED' | 'IDLE' | 'DIRTY' | 'QUEUE';

// --- Alert Definition (from taxonomy) ---

export interface AlertDefinition {
  id: string;
  name: string;
  description: string;
  category: 'floor' | 'kitchen' | 'manager' | 'system';
  severity: Severity;
  trigger: string; // Human-readable trigger description
  recipient: RecipientRole;
  escalate_after_seconds: number | null;
  escalate_to: RecipientRole | null;
  cooldown_seconds: number;
  dedupe_key: string;
}

// --- Zone ---

export interface Zone {
  id: string;
  name: string;
  type: 'dining' | 'entry' | 'pass' | 'bar';
  tableCount: number;
}

// --- Zone Occupancy Snapshot ---

export interface ZoneSnapshot {
  zoneId: string;
  state: ZoneState;
  blobCount: number;
  seatedCount: number;
  standingCount: number;
  staffPresent: boolean;
  /** Seconds since last state transition */
  stateDurationSeconds: number;
  /** Seconds since last staff blob was detected in zone */
  secondsSinceStaffVisit: number;
  /** Number of occupied tables (if known) */
  occupiedTables: number;
  /** Total tables in zone */
  totalTables: number;
}

// --- Restaurant State ---

export interface RestaurantState {
  restaurantId: string;
  timestamp: Date;
  zones: Map<string, ZoneSnapshot>;
  /** Current system mode */
  mode: 'FULL' | 'QUIET' | 'OFF';
  /** Muted zone IDs with expiry */
  mutedZones: Map<string, Date>;
}

// --- Alert Instance (generated by rules engine) ---

export interface Alert {
  id: string;
  definitionId: string;
  zoneId: string;
  severity: Severity;
  text: string;
  recipient: RecipientRole;
  escalationTier: number;
  createdAt: Date;
  state: 'new' | 'delivered' | 'acknowledged' | 'snoozed' | 'resolved' | 'overridden' | 'escalated';
  dedupeKey: string;
}
